# -*- coding: utf-8 -*-
# Part of NexAML. See LICENSE file for full copyright and licensing details.

from odoo import api, fields, models, _
from odoo.tools.safe_eval import safe_eval


class TransactionRule(models.Model):
    """Configurable transaction monitoring rules."""
    _name = 'aml.transaction.rule'
    _description = 'Transaction Monitoring Rule'
    _order = 'sequence, name'

    name = fields.Char(
        string='Rule Name',
        required=True,
        help='Name of the monitoring rule'
    )
    code = fields.Char(
        string='Rule Code',
        required=True,
        help='Unique code for this rule (e.g., HIGH_VALUE, VELOCITY)'
    )
    sequence = fields.Integer(
        string='Sequence',
        default=10,
        help='Order in which rules are evaluated'
    )
    rule_type = fields.Selection(
        [('threshold', 'Amount Threshold'),
         ('velocity', 'Transaction Velocity'),
         ('pattern', 'Pattern Matching')],
        string='Rule Type',
        required=True,
        default='threshold',
        help='Type of monitoring rule'
    )
    active = fields.Boolean(
        default=True,
        help='Whether this rule is active'
    )

    # Threshold Rule Fields
    amount_threshold = fields.Monetary(
        string='Amount Threshold',
        currency_field='currency_id',
        help='Alert when transaction amount exceeds this value'
    )
    currency_id = fields.Many2one(
        'res.currency',
        string='Currency',
        default=lambda self: self.env.company.currency_id,
        help='Currency for amount threshold'
    )

    # Velocity Rule Fields
    period_days = fields.Integer(
        string='Period (Days)',
        default=1,
        help='Time period for velocity calculation'
    )
    transaction_count = fields.Integer(
        string='Transaction Count',
        help='Alert when transaction count exceeds this in the period'
    )
    velocity_amount = fields.Monetary(
        string='Velocity Amount',
        currency_field='currency_id',
        help='Alert when total amount exceeds this in the period'
    )

    # Pattern Rule Fields
    domain_filter = fields.Text(
        string='Domain Filter',
        help='Odoo domain filter for pattern matching (e.g., [("amount_total", ">", 10000)])'
    )

    # Risk Level Filtering
    applies_to_risk_level = fields.Selection(
        [('all', 'All Customers'),
         ('low', 'Low Risk Only'),
         ('medium', 'Medium Risk and Above'),
         ('high', 'High Risk Only')],
        string='Applies To',
        default='all',
        help='Which customer risk levels this rule applies to'
    )

    # Alert Configuration
    alert_severity = fields.Selection(
        [('low', 'Low'),
         ('medium', 'Medium'),
         ('high', 'High'),
         ('critical', 'Critical')],
        string='Alert Severity',
        required=True,
        default='medium',
        help='Severity of alerts generated by this rule'
    )
    alert_message = fields.Text(
        string='Alert Message',
        help='Custom message for alerts generated by this rule'
    )
    description = fields.Text(
        string='Description',
        help='Description of what this rule monitors'
    )

    _sql_constraints = [
        ('code_unique', 'UNIQUE(code)', 'Rule code must be unique!')
    ]

    def evaluate(self, move):
        """Evaluate if this rule triggers for the given transaction.

        Args:
            move: account.move record to evaluate

        Returns:
            dict: {'triggered': bool, 'reason': str, 'details': dict}
        """
        self.ensure_one()

        # Check if rule applies to partner's risk level
        if not self._applies_to_partner(move.partner_id):
            return {'triggered': False, 'reason': 'Risk level not applicable'}

        # Evaluate based on rule type
        if self.rule_type == 'threshold':
            return self._evaluate_threshold(move)
        elif self.rule_type == 'velocity':
            return self._evaluate_velocity(move)
        elif self.rule_type == 'pattern':
            return self._evaluate_pattern(move)

        return {'triggered': False, 'reason': 'Unknown rule type'}

    def _applies_to_partner(self, partner):
        """Check if rule applies to partner's risk level."""
        if not partner or self.applies_to_risk_level == 'all':
            return True

        partner_risk = partner.risk_level or 'low'

        if self.applies_to_risk_level == 'low':
            return partner_risk == 'low'
        elif self.applies_to_risk_level == 'medium':
            return partner_risk in ('medium', 'high')
        elif self.applies_to_risk_level == 'high':
            return partner_risk == 'high'

        return True

    def _evaluate_threshold(self, move):
        """Evaluate amount threshold rule."""
        if not self.amount_threshold:
            return {'triggered': False, 'reason': 'No threshold configured'}

        amount = abs(move.amount_total)

        if amount > self.amount_threshold:
            return {
                'triggered': True,
                'reason': f'Amount {amount:.2f} exceeds threshold {self.amount_threshold:.2f}',
                'details': {
                    'amount': amount,
                    'threshold': self.amount_threshold,
                }
            }

        return {'triggered': False, 'reason': 'Below threshold'}

    def _evaluate_velocity(self, move):
        """Evaluate transaction velocity rule."""
        if not move.partner_id:
            return {'triggered': False, 'reason': 'No partner'}

        # Calculate date range
        date_from = fields.Date.subtract(move.date, days=self.period_days)

        # Find transactions in period
        domain = [
            ('partner_id', '=', move.partner_id.id),
            ('date', '>=', date_from),
            ('date', '<=', move.date),
            ('state', '=', 'posted'),
            ('move_type', 'in', ['out_invoice', 'in_invoice']),
            ('id', '!=', move.id),  # Exclude current transaction
        ]

        recent_moves = self.env['account.move'].search(domain)
        count = len(recent_moves) + 1  # Include current move
        total_amount = sum(abs(m.amount_total) for m in recent_moves) + abs(move.amount_total)

        triggered = False
        reasons = []

        if self.transaction_count and count > self.transaction_count:
            triggered = True
            reasons.append(f'{count} transactions in {self.period_days} days (limit: {self.transaction_count})')

        if self.velocity_amount and total_amount > self.velocity_amount:
            triggered = True
            reasons.append(f'Total amount {total_amount:.2f} exceeds limit {self.velocity_amount:.2f}')

        if triggered:
            return {
                'triggered': True,
                'reason': '; '.join(reasons),
                'details': {
                    'transaction_count': count,
                    'total_amount': total_amount,
                    'period_days': self.period_days,
                }
            }

        return {'triggered': False, 'reason': 'Velocity within limits'}

    def _evaluate_pattern(self, move):
        """Evaluate pattern matching rule."""
        if not self.domain_filter:
            return {'triggered': False, 'reason': 'No pattern configured'}

        try:
            domain = safe_eval(self.domain_filter)
            if not isinstance(domain, list):
                return {'triggered': False, 'reason': 'Invalid domain format'}

            # Check if current move matches domain
            matching = self.env['account.move'].search([('id', '=', move.id)] + domain)

            if matching:
                return {
                    'triggered': True,
                    'reason': f'Transaction matches pattern: {self.domain_filter}',
                    'details': {
                        'pattern': self.domain_filter,
                    }
                }

            return {'triggered': False, 'reason': 'Pattern not matched'}

        except Exception as e:
            return {'triggered': False, 'reason': f'Pattern evaluation error: {str(e)}'}
